### ISSUE TITLE
Any interest in collaborating / merging with awesome-open-company?

### ISSUE THREAD

**Issue by waldyrious** [paulhendricks/awesome-open#2]
https://github.com/opencompany/awesome-open-company

Note: I'm the original creator of that repo, and actively maintain it. I'm very much open to collaboration :)

**Comment by paulhendricks** [comment]
I would love to link to your collection and contribute as needed! You're welcome to do the same. A goal of mine in collecting these organizations was to keep them narrowly focused on code bases; e.g. Gitub, Bitbucket, Gitlab, etc. 

Do you see that focus overlapping with your focuses and duplicating your work?

**Comment by waldyrious** [comment]
Well, I'm particularly interested in for-profit organizations. The goal of the Open Company Initiative is to showcase how an open operation model can fit with a commercial project, since the prevailing view is that they are not compatible. In that sense, the overlap could occur in the "open organizations" part of this project's subject ("Open Organizations and Communities").

If you're focusing on codebases, then there won't be much duplicated work, but if you start including for-profit organizations,  I'd love to keep both our lists in sync in that aspect.

**Comment by paulhendricks** [comment]
Completely reasonable, and I absolutely agree. I'm going to add a link to your organization as well. Would you mind doing the same for mine?

**Comment by waldyrious** [comment]
Great, then :) I will add the link to the "[similar lists](https://github.com/opencompany/awesome-open-company#similar-lists)" section as soon as [PR#27](https://github.com/opencompany/awesome-open-company/pull/27) is merged.

**Comment by waldyrious** [comment]
https://github.com/opencompany/awesome-open-company/commit/63661ec
